#   ______ _____ _    _ _____   _____ 
# |___  // ____| |  | |  __ \ / ____|
#    / /| (___ | |__| | |__) | |     
#   / /  \___ \|  __  |  _  /| |     
#  / /__ ____) | |  | | | \ \| |____ 
# /_____|_____/|_|  |_|_|  \_\\_____|

# Includes
source ~/.zsh/paths.zsh
source ~/.zsh/general.zsh

# Plugins
source ~/.zsh/pure.zsh
source ~/.zsh/bundles.zsh
source ~/.zsh/dotnet.zsh