SPACESHIP_EXIT_CODE_SHOW=true
SPACESHIP_TIME_SHOW=true
SPACESHIP_DIR_TRUNC=0
SPACESHIP_VENV_SYMBOL="🐍"
SPACESHIP_DOCKER_SYMBOL="🐳"
SPACESHIP_GIT_SYMBOL=""
SPACESHIP_PYENV_SHOW=false
SPACESHIP_VENV_COLOR=green
