# Show all operations and how long it's taking for them to complete
#setopt prompt_subst; zmodload zsh/datetime; PS4='+[$EPOCHREALTIME]%N:%i> '; set -x

start=$(date +%s%N | cut -b1-13)

source ~/.zsh/includes/general.zsh

if [[ $platform == 'darwin' ]]; then
    source ~/.zsh/includes/brew.zsh
fi

source ~/.zsh/includes/powerlevel9k.zsh

source ~/.zsh/includes/golang.zsh

source ~/.zsh/includes/python.zsh

source ~/.zsh/includes/alias.zsh

source ~/.zsh/includes/rvm.zsh

source ~/.zsh/includes/node.zsh

plugins_start=$(date +%s%N | cut -b1-13)
source ~/.zsh/includes/plugins.zsh
plugins_end=$(date +%s%N | cut -b1-13)

source ~/.zsh/includes/pyenv.zsh

source ~/.zsh/includes/fzf.zsh

source ~/.zsh/includes/git.zsh

##source ~/.zsh/includes/android.zsh

##source ~/.zsh/includes/cocos.zsh

##cat ~/.zsh/includes/triforce.ascii

## Rust
export PATH="$HOME/.cargo/bin:$PATH"

if [[ "$platform" == "windows" ]]; then
    source ~/.zsh/includes/windows.zsh
fi

cd ~

echo "ZSH plugins load time:  $(expr $plugins_end - $plugins_start)ms"
echo "ZSH total startup time: $(expr $(date +%s%N | cut -b1-13) - $start)ms"
